### ISSUE TITLE
Failed to import python module pegasus.simulator. Error: No module named 'rclpy'.

### ISSUE THREAD

**Issue by DuaneNielsen** [PegasusSimulator/PegasusSimulator#17]
whilst following the install instructions...

Ubuntu 20.04
IsaacSim 2023.1.0
ROS noetic installed

seems like the rclpy extension is not correctly setup as a dependency

[9525.730s] [ext: pegasus.simulator-1.0.0] startup
2023-12-07 20:07:28 [9,525,702ms] [Warning] [omni.isaac.core.utils.nucleus] /persistent/app/omniverse/mountedDrives setting not found
[9525.762s] [ext: omni.isaac.ros2_bridge-2.3.9] startup
2023-12-07 20:07:28 [9,525,772ms] [Error] [omni.isaac.ros2_bridge.scripts.extension] ROS_DISTRO of noetic is currently not supported
2023-12-07 20:07:28 [9,526,133ms] [Error] [omni.ext._impl.custom_importer] Failed to import python module pegasus.simulator. Error: No module named 'rclpy'. Traceback:
Traceback (most recent call last):
  File "/home/duane/.local/share/ov/pkg/isaac_sim-2023.1.0-hotfix.1/kit/kernel/py/omni/ext/_impl/custom_importer.py", line 76, in import_module
    return importlib.import_module(name)
  File "/home/duane/.local/share/ov/pkg/isaac_sim-2023.1.0-hotfix.1/kit/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/duane/PegasusSimulator/extensions/pegasus.simulator/pegasus/simulator/__init__.py", line 9, in <module>
    from .extension import Pegasus_SimulatorExtension
  File "/home/duane/PegasusSimulator/extensions/pegasus.simulator/pegasus/simulator/extension.py", line 31, in <module>
    from pegasus.simulator.ui.ui_window import WidgetWindow
  File "/home/duane/PegasusSimulator/extensions/pegasus.simulator/pegasus/simulator/ui/__init__.py", line 5, in <module>
    from .ui_delegate import UIDelegate
  File "/home/duane/PegasusSimulator/extensions/pegasus.simulator/pegasus/simulator/ui/ui_delegate.py", line 22, in <module>
    from pegasus.simulator.logic.backends import MavlinkBackend, MavlinkBackendConfig #, ROS2Backend
  File "/home/duane/PegasusSimulator/extensions/pegasus.simulator/pegasus/simulator/logic/backends/__init__.py", line 8, in <module>
    from .ros2_backend import ROS2Backend
  File "/home/duane/PegasusSimulator/extensions/pegasus.simulator/pegasus/simulator/logic/backends/ros2_backend.py", line 16, in <module>
    import rclpy
ModuleNotFoundError: No module named 'rclpy'

2023-12-07 20:07:28 [9,526,133ms] [Error] [carb.scripting-python.plugin] Exception: Extension python module: 'pegasus.simulator' in '/home/duane/PegasusSimulator/extensions/pegasus.simulator' failed to load.

At:
  /home/duane/.local/share/ov/pkg/isaac_sim-2023.1.0-hotfix.1/kit/kernel/py/omni/ext/_impl/_internal.py(213): startup
  /home/duane/.local/share/ov/pkg/isaac_sim-2023.1.0-hotfix.1/kit/kernel/py/omni/ext/_impl/_internal.py(328): startup_extension
  PythonExtension.cpp::startup()(2): <module>
  /home/duane/.local/share/ov/pkg/isaac_sim-2023.1.0-hotfix.1/kit/exts/omni.kit.window.extensions/omni/kit/window/extensions/ext_commands.py(29): do
  /home/duane/.local/share/ov/pkg/isaac_sim-2023.1.0-hotfix.1/kit/exts/omni.kit.commands/omni/kit/undo/undo.py(80): execute
  /home/duane/.local/share/ov/pkg/isaac_sim-2023.1.0-hotfix.1/kit/exts/omni.kit.commands/omni/kit/commands/command.py(463): execute
  /home/duane/.local/share/ov/pkg/isaac_sim-2023.1.0-hotfix.1/kit/exts/omni.kit.window.extensions/omni/kit/window/extensions/common.py(288): toggle_extension
  /home/duane/.local/share/ov/pkg/isaac_sim-2023.1.0-hotfix.1/kit/exts/omni.kit.window.extensions/omni/kit/window/extensions/ext_components.py(93): toggle

2023-12-07 20:07:28 [9,526,133ms] [Error] [omni.ext.plugin] [ext: pegasus.simulator-1.0.0] Failed to startup python extension.
[9526.884s] [ext: omni.isaac.ros2_bridge-2.3.9] shutdown

**Comment by DuaneNielsen** [comment]
I think this occurs because ROS noetic is not supported.  Closing issue.

For anyone wanting to work with ROS1, you can resolve this problem by opening

PegasusSimulator/extensions/pegasus.simulator/pegasus/simulator/init.py

and commenting out the ROS2Backend.

```
from .backend import Backend
from .mavlink_backend import MavlinkBackend, MavlinkBackendConfig
# from .ros2_backend import ROS2Backend
```

**Comment by DuaneNielsen** [comment]
Alternatively, you could also try

```
from omni.isaac.core.utils.extensions import get_extension_id

from .backend import Backend
from .mavlink_backend import MavlinkBackend, MavlinkBackendConfig

if get_extension_id("omni.isaac.ros2_bridge") is not None:
    from .ros2_backend import ROS2Backend
```

I think this should enable the ROS2Backend only when the ros2_bridge is loaded
